In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
import pandas as pd
import numpy as np
import os

In [3]:
import hypopredict.cv as cv

In [4]:
# hand-picked TEST days and DEMO days are held out already
# make sure the number of days is divisible by K for K-fold CV
non_test_days = [12, 21, 13, 24, 31, 34, 42, 44, 52, 11, 72, 74]

In [5]:
ECG_PATH = os.getenv('ECG_PATH')
ECG_PATH

'/Users/alexxela/code/hypopredict/data/feathers/'

In [6]:
splitter = cv.CV_splitter(n_splits=4,
                       random_state=17,
                       ecg_dir=ECG_PATH,
                       glucose_src='local'
                       )

In [7]:
splitter

In [8]:
splitter.__dict__

{'n_splits': 4,
 'random_state': 17,
 'ecg_dir': '/Users/alexxela/code/hypopredict/data/feathers/',
 'glucose_src': 'local'}

In [9]:
splits = splitter.get_splits(non_test_days)

In [10]:
# people are shuffled
# days are shuffled because we test only full days
# and our features are day-based
splits

[array([13, 21, 74]),
 array([44, 42, 24]),
 array([52, 31, 11]),
 array([72, 34, 12])]

In [11]:
# validate needs GLUCOSE_PATH env var set
_ = os.getenv('GLUCOSE_PATH')
_

'/Users/alexxela/code/hypopredict/data/dbt-glucose/'

In [13]:
checks, props = splitter.validate(splits)

--------------------------------------------------
Validating split: [13 21 74]

    Files concatinated:
                 ['/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-21-12_35_54-1HG.feather', '/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-21-20_29_57-1HG.feather']
--------------------------------------------------
Validating split: [44 42 24]

    Files concatinated:
                 ['/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-44-06_32_58-1HG.feather', '/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-44-16_49_30-1HG.feather']

    Files concatinated:
                 ['/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-24-17_43_12-2HG.feather', '/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-24-07_01_03-2HG.feather']
--------------------------------------------------
Validating split: [52 31 11]

    Files concatinated:
                 ['/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-52-09_23_58-

In [14]:
checks, props

([np.True_, np.True_, np.False_, np.False_],
 [np.float64(0.2625),
  np.float64(0.0401),
  np.float64(0.0),
  np.float64(-33.3333)])

In [16]:
splitter.validate(splits, verbose=True)

--------------------------------------------------
Validating split: [13 21 74]

    Files concatinated:
                 ['/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-21-12_35_54-1HG.feather', '/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-21-20_29_57-1HG.feather']

Split [13 21 74] is valid with 26.25% of y == 1

--------------------------------------------------
Validating split: [44 42 24]

    Files concatinated:
                 ['/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-44-06_32_58-1HG.feather', '/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-44-16_49_30-1HG.feather']

    Files concatinated:
                 ['/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-24-17_43_12-2HG.feather', '/Users/alexxela/code/hypopredict/data/feathers/EcgWaveform-24-07_01_03-2HG.feather']

Split [44 42 24] is valid with 4.01% of y == 1

--------------------------------------------------
Validating split: [52 31 11]

    Files conca

([np.True_, np.True_, np.False_, np.False_],
 [np.float64(0.2625),
  np.float64(0.0401),
  np.float64(0.0),
  np.float64(-33.3333)])